### ISSUE TITLE
Cannot load the data

### ISSUE THREAD

**Issue by dieunelderilus** [hbctraining/Training-modules#14]
Hello hbctraining

I am trying to repeat this tutorial  here (https://hbctraining.github.io/Training-modules/Visualization_in_R/lessons/03_advanced_visualizations.html).  I am a beginner in R, and  I don't even see how to load in  the data used for this tutorial. I am getting this error at the first command line :
> res_tableOE_ordered <- res_tableOE[order(res_tableOE$padj), ]
Error: object 'res_tableOE' not found

Please how I can load the data?

Cordially
~DD

**Comment by rkhetani** [comment]
Please go through all there lessons on this workshop. More information and lesson links are here - https://hbctraining.github.io/Training-modules/Visualization_in_R/

**Comment by dieunelderilus** [comment]
Thank you for your quick response!

Cordially
~DD

___________________

*Dieunel Derilus, PhD*

Environmental Biologist

Guest Researcher - APHL Postdoctoral Bioinformatics Fellow

Insecticide Resistance and Vector Control Team

U.S. Centers for Disease Control and Prevention (CDC)

1600 Clifton Rd. NE, MS G-49; Bldg. 23 cubicle 11-110; Atlanta, GA 30329 USA

Email: qlk5@cdc.gov / dieunelderilus@gmail.com

Tel: +1 787 513 4667
